[package]
name = "ridser"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
axum = "0.6.12"
axum-macros = "0.3.7"
dotenvy = "0.15.7"
openidconnect = "2.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.27.0", features = [
    "fs",
    "macros",
    "rt-multi-thread",
    "signal",
] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"
