[package]
name = "ridser"
version = "0.1.0"
authors = ["Erik Wegner"]
edition = "2021"

[lib]
path = "./src/lib/lib.rs"

[dependencies]
dotenv = "0.15.0"
futures = "0.3.17"
hmac = "0.11"
jwt = "0.15.0"
once_cell = "1.4.0"
parking_lot = "0.11"
redis = { version = "0.21.4", features = [
    "tokio-comp",
    "connection-manager",
    "aio",
] }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"
tokio = { version = "1.14", features = ["sync", "time"] }
ureq = "2"
url = "2.2.2"
