[package]
name = "ridser"
version = "0.2.0"
authors = ["Erik Wegner"]
edition = "2021"

[dependencies]
async-std = "1.10.0"
crossbeam = "0.8.1"
dashmap = "5.0.0"
dotenv = "0.15.0"
futures = "0.3.17"
hmac = "0.11"
jwt = { version = "0.15.0", features = ["openssl"] }
once_cell = "1.4.0"
openssl = { version = "0.10" }
parking_lot = "0.11"
simple_redis = "^0.6.1"
reqwest = { version = "0.11", features = ["default", "json", "multipart"] }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"
tokio = { version = "1.14", features = ["sync", "time"] }
url = "2.2.2"

[dev-dependencies]
rand = "0.8.4"
tokio-test = "0.4.2"
wiremock = "0.5.8"
