version: '3'
services:
  ridser:
    image: mcr.microsoft.com/vscode/devcontainers/rust:bullseye
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - redis

  redis:
    image: redis:6.2.6-alpine

  keycloak:
    image: bitnami/keycloak:15.0.2
    ports:
      - "8100:8080"
      - "8101:8443"
