version: '3'
services:
  ridser:
    # https://mcr.microsoft.com/v2/vscode/devcontainers/rust/tags/list
    image: mcr.microsoft.com/vscode/devcontainers/rust:bullseye
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  redis:
    image: redis:6.2.6-alpine

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command: [ "start-dev" ]
    ports:
      - "8101:8443"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/dev_realm.json
    volumes:
      - ./dev_realm.json:/tmp/dev_realm.json
