version: '3'
services:
  ridser:
    # https://mcr.microsoft.com/v2/vscode/devcontainers/rust/tags/list
    image: mcr.microsoft.com/devcontainers/rust:0-1-bullseye
    volumes:
      # Mount the root folder that contains .git
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  redis:
    image: redis:6.2.6-alpine

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command:
      - start-dev
      - --import-realm
    ports:
      - "8101:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ../dev_realm.json:/opt/keycloak/data/import/dev_realm.json
