http:
  routers:
    keycloak:
      rule: PathPrefix(`/`)
      entryPoints:
        - keycloak
      service: keycloak
    ridser:
      rule: PathPrefix(`/`)
      entryPoints:
        - ridser
      service: ridser
    ridser-forward-auth-route:
      rule: PathPrefix(`/api/fwauth`)
      entryPoints:
        - ridser
      service: rsecho
      middlewares:
        - ridser-forward-auth-middleware
    dashboard:
      rule: "PathPrefix(`/traefik/dashboard`) || PathPrefix(`/traefik/api`)"
      entryPoints:
        - ridser
        - keycloak
      service: api@internal

  middlewares:
    ridser-forward-auth-middleware:
      forwardAuth:
        address: "http://ridser:3000/auth"
        authResponseHeaders:
          - "Authorization"
          - "Cookie"

  services:
    keycloak:
      loadBalancer:
        servers:
          - url: "http://ridser:8101"
    ridser:
      loadBalancer:
        servers:
          - url: "http://ridser:3000"
    rsecho:
      loadBalancer:
        servers:
          - url: "http://echo:3000"
